import { MaintenanceStatus, MaintenanceUrgency } from '@shared/enums/maintenance.enum';

export class MaintenanceRequestEntity {
    constructor(
        public readonly id: string,
        public readonly requestNumber: string,
        public readonly propertyId: string,
        public readonly tenantId: string,
        public readonly ownerId: string,
        public readonly issueType: string,
        public readonly issueTitle: string,
        public readonly issueDescription: string,
        public readonly urgencyLevel: MaintenanceUrgency | string,
        public readonly photos: string[],
        public readonly preferredVisitDate: Date | null,
        public readonly preferredVisitTimeStart: Date | null,
        public readonly preferredVisitTimeEnd: Date | null,
        public readonly availableAnytime: boolean,
        public readonly assignedProviderId: string | null,
        public readonly providerAcceptedAt: Date | null,
        public readonly providerEtaMinutes: number | null,
        public readonly providerArrivalTime: Date | null,
        public readonly status: MaintenanceStatus | string,
        public readonly workStartedAt: Date | null,
        public readonly workCompletedAt: Date | null,
        public readonly completionPhotos: string[],
        public readonly workDescription: string | null,
        public readonly actualCost: number | null,
        public readonly costPaidBy: string | null,
        public readonly isVerifiedByTenant: boolean,
        public readonly tenantVerificationStatus: string | null,
        public readonly tenantRating: number | null,
        public readonly tenantFeedback: string | null,
        public readonly verifiedAt: Date | null,
        public readonly isDisputed: boolean,
        public readonly disputeReason: string | null,
        public readonly submittedAt: Date,
        public readonly updatedAt: Date,
        public readonly closedAt: Date | null,
        public readonly propertyTitle?: string,
        public readonly tenantName?: string,
        public readonly providerName?: string,
    ) {}
}
