import { Router } from 'express';
import { container } from 'tsyringe';
import { UserRoutes } from './auth/user.routes';
import { AdminRoutes } from './admin/admin.routes';
import { OwnerRoutes } from './owner/owner.routes';
import { ProfileRoutes } from './profile/profile.routes';
import { API_PREFIXES } from '@shared/constants/routes';
import { PropertyRoutes } from './property/property.routes';
import { ServiceProviderRoutes } from './property/service-provider.routes';
import { WishlistRoutes } from './property/wishlist.routes';
const router = Router();
const userRoutes = container.resolve(UserRoutes);
const adminRoutes = container.resolve(AdminRoutes);
const ownerRoutes = container.resolve(OwnerRoutes);
const profileRoutes = container.resolve(ProfileRoutes);
const propertyRoutes = container.resolve(PropertyRoutes);
const serviceProviderRoutes = container.resolve(ServiceProviderRoutes);
const wishlistRoutes = container.resolve(WishlistRoutes);

router.use(API_PREFIXES.AUTH, userRoutes.router);
router.use(API_PREFIXES.ADMIN, adminRoutes.router);
router.use(API_PREFIXES.OWNER, ownerRoutes.router);
router.use(API_PREFIXES.PROFILE, profileRoutes.router);
router.use(API_PREFIXES.PROPERTY, propertyRoutes.router);
router.use(API_PREFIXES.SERVICE_PROVIDER, serviceProviderRoutes.router);
router.use(API_PREFIXES.WISHLIST, wishlistRoutes.router);
export default router;
