import { Router } from 'express';
import { container } from 'tsyringe';
import { UserRoutes } from './auth/user.routes';
import { AdminRoutes } from './admin/admin.routes';
import { OwnerRoutes } from './owner/owner.routes';
import { ProfileRoutes } from './profile/profile.routes';
import { API_PREFIXES } from '@shared/constants/routes';
import { PropertyRoutes } from './property/property.routes';
import { ServiceProviderRoutes } from './property/service-provider.routes';
import { WishlistRoutes } from './property/wishlist.routes';
import { AgreementRoutes } from './agreement.routes';
import { NotificationRoutes } from './notification/notification.routes';
import { PaymentRoutes } from './payment.routes';
import { ChatRoutes } from './chat/chat.routes';
import { MaintenanceRoutes } from './maintenance/maintenance.routes';
const router = Router();
const userRoutes = container.resolve(UserRoutes);
const adminRoutes = container.resolve(AdminRoutes);
const ownerRoutes = container.resolve(OwnerRoutes);
const profileRoutes = container.resolve(ProfileRoutes);
const propertyRoutes = container.resolve(PropertyRoutes);
const serviceProviderRoutes = container.resolve(ServiceProviderRoutes);
const wishlistRoutes = container.resolve(WishlistRoutes);
const agreementRoutes = container.resolve(AgreementRoutes);
const notificationRoutes = container.resolve(NotificationRoutes);
const paymentRoutes = container.resolve(PaymentRoutes);
const chatRoutes = container.resolve(ChatRoutes);
const maintenanceRoutes = container.resolve(MaintenanceRoutes);
router.use(API_PREFIXES.AUTH, userRoutes.router);
router.use(API_PREFIXES.ADMIN, adminRoutes.router);
router.use(API_PREFIXES.OWNER, ownerRoutes.router);
router.use(API_PREFIXES.PROFILE, profileRoutes.router);
router.use(API_PREFIXES.PROPERTY, propertyRoutes.router);
router.use(API_PREFIXES.SERVICE_PROVIDER, serviceProviderRoutes.router);
router.use(API_PREFIXES.WISHLIST, wishlistRoutes.router);
router.use(API_PREFIXES.AGREEMENT, agreementRoutes.router);
router.use(API_PREFIXES.NOTIFICATION, notificationRoutes.router);
router.use(API_PREFIXES.PAYMENT, paymentRoutes.router);
router.use(API_PREFIXES.CHAT, chatRoutes.router);
router.use(API_PREFIXES.MAINTENANCE, maintenanceRoutes.router);
export default router;
