export enum NotificationType {
    OWNER_VERIFICATION_APPROVED = 'OWNER_VERIFICATION_APPROVED',
    OWNER_VERIFICATION_REJECTED = 'OWNER_VERIFICATION_REJECTED',

    PROPERTY_APPROVED = 'PROPERTY_APPROVED',
    PROPERTY_REJECTED = 'PROPERTY_REJECTED',
    PROPERTY_UNLISTED = 'PROPERTY_UNLISTED',

    USER_SUSPENDED = 'USER_SUSPENDED',

    AGREEMENT_CREATED = 'AGREEMENT_CREATED',
    AGREEMENT_SIGNED = 'AGREEMENT_SIGNED',

    NEW_MESSAGE = 'NEW_MESSAGE',
}


// export enum NotificationType {
//     OWNER_VERIFIED = 'OWNER_VERIFIED',
//     OWNER_REJECTED = 'OWNER_REJECTED',

//     PROPERTY_APPROVED = 'PROPERTY_APPROVED',
//     PROPERTY_REJECTED = 'PROPERTY_REJECTED',

//     USER_SUSPENDED = 'USER_SUSPENDED',

//     AGREEMENT_SENT = 'AGREEMENT_SENT',
//     AGREEMENT_SIGNED = 'AGREEMENT_SIGNED',

//     SYSTEM = 'SYSTEM',
// }