export enum NotificationType {
    OWNER_VERIFIED = 'OWNER_VERIFIED',
    OWNER_REJECTED = 'OWNER_REJECTED',

    PROPERTY_APPROVED = 'PROPERTY_APPROVED',
    PROPERTY_REJECTED = 'PROPERTY_REJECTED',

    USER_SUSPENDED = 'USER_SUSPENDED',

    AGREEMENT_SENT = 'AGREEMENT_SENT',
    AGREEMENT_SIGNED = 'AGREEMENT_SIGNED',

    SYSTEM = 'SYSTEM',
}