export enum NotificationType {
    OWNER_VERIFICATION_APPROVED = 'OWNER_VERIFICATION_APPROVED',
    OWNER_VERIFICATION_REJECTED = 'OWNER_VERIFICATION_REJECTED',
    OWNER_VERIFICATION_SUBMITTED = 'OWNER_VERIFICATION_SUBMITTED',

    PROPERTY_APPROVED = 'PROPERTY_APPROVED',
    PROPERTY_REJECTED = 'PROPERTY_REJECTED',
    PROPERTY_UNLISTED = 'PROPERTY_UNLISTED',
    PROPERTY_SUBMITTED = 'PROPERTY_SUBMITTED',

    USER_SUSPENDED = 'USER_SUSPENDED',

    AGREEMENT_CREATED = 'AGREEMENT_CREATED',
    AGREEMENT_SIGNED = 'AGREEMENT_SIGNED',

    NEW_MESSAGE = 'NEW_MESSAGE',
}
