//uses tokens insted of class is beacause interfaces doesnt exist at runtime.
// so the tokens will be as identifiers used for DI

export const TokenTypes = {
    IUserRepository: 'IUserRepository',
    ICreateUserUseCase: 'ICreateUserUseCase',
    IVerifyOtpUseCase: 'IVerifyOtpUseCase',
    IHashService: 'IHashService',
    IOtpService: 'IOtpService',
    IMailService: 'IMailService',
    IRedisCache: 'IRedisCache',
    IJwtService: 'IJwtService',
    IResendOtpUseCase: 'IResendOtpUseCase',
    ILoginUseCase: 'ILoginUseCase',
    IForgotPasswordUseCase: 'IForgotPasswordUseCase',
    IFirebaseService: 'IFirebaseService',
    IGoogleAuthUseCase: 'IGoogleAuthUseCase',
    UserManagementUseCase: 'UserManagementUseCase',
    AdminUserManagementUseCase: 'AdminUserManagementUseCase',
    IRefreshTokenUseCase: 'IRefreshTokenUseCase',
    IOwnerProfileRepository: 'IOwnerProfileRepository',
    ITenantProfileRepository: 'ITenantProfileRepository',
    SubmitVerificationUseCase: 'SubmitVerificationUseCase',
    VerifyOwnerUseCase: 'VerifyOwnerUseCase',
    GetProfileUseCase: 'GetProfileUseCase',
    UpdateProfileUseCase: 'UpdateProfileUseCase',
    IPropertyRepository: 'IPropertyRepository',
    IServiceProviderRepository: 'IServiceProviderRepository',
    IWishlistRepository: 'IWishlistRepository',
    ICreatePropertyUseCase: 'ICreatePropertyUseCase',
    IGetPropertyByIdUseCase: 'IGetPropertyByIdUseCase',
    IUpdatePropertyUseCase: 'IUpdatePropertyUseCase',
    IUnlistPropertyUseCase: 'IUnlistPropertyUseCase',
    IDeletePropertyUseCase: 'IDeletePropertyUseCase',
    IServiceProviderUseCase: 'IServiceProviderUseCase',
    IWishlistUseCase: 'IWishlistUseCase',
    IVerifyPropertyUseCase: 'IVerifyPropertyUseCase',
    IGetMyPropertiesUseCase: 'IGetMyPropertiesUseCase',
    IGetAllPropertiesUseCase: 'IGetAllPropertiesUseCase',
    IS3Service: 'IS3Service',
    IModerationService: 'IModerationService',
    IRelistPropertyUseCase: 'IRelistPropertyUseCase',
};
